Create Table Commints (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    UserId BIGINT DEFAULT TRUE,
    PostId BIGINT DEFAULT TRUE,
    IsActive BOOLEAN DEFAULT TRUE,
    FOREIGN KEY(UserId) REFERENCES users(id) on DELETE CASCADE,
    FOREIGN KEY (PostId) REFERENCES posts(id) on DELETE CASCADE
);
CREATE TABLE Commints (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    UserId BIGINT UNSIGNED DEFAULT NULL,  
    PostId BIGINT UNSIGNED DEFAULT NULL,  
    IsActive BOOLEAN DEFAULT TRUE,
    FOREIGN KEY(UserId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(PostId) REFERENCES posts(id) ON DELETE CASCADE
);
